schema_version = "1.0.0"

id = "touchview"
version = "4.2.0"
name = "Touch Viewport"
tagline = "Creates active touch zones over View 2D and 3D areas for easier viewport navigation with touch screens and pen tablets"
maintainer = "NENDO, Karan(b3dhub)"
type = "add-on"

permissions = ["files"]

website = "https://github.com/nendotools/touchview"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/extensions/tags.html
tags = ["3D View", "User Interface"]

blender_version_min = "4.2.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
license = ["SPDX:GPL-2.0-or-later"]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "docs/",
  ".gitignore",
  "/*.zip",
  "/bin",
  "settings.json",
  "bundle.sh",
  "mypy.ini",
  "requirements.txt",
  "README.md"
]
