schema_version = "1.0.0"

id = "touchview"
version = "4.2.1"
name = "Touch Viewport"
tagline = "Creates active touch zones over View 2D and 3D areas"
maintainer = "NENDO, Karan(b3dhub)"
type = "add-on"

website = "https://github.com/nendotools/touchview"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/extensions/tags.html
tags = ["3D View", "User Interface"]

blender_version_min = "4.2.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
license = ["SPDX:GPL-3.0-or-later"]

[permissions]
files = "preserve settings when enabling/disabling the add-on"

[build]
paths_exclude_pattern = [
    "__pycache__/",
    "/.git/",
    "docs/",
    ".gitignore",
    "/*.zip",
    "/bin",
    "settings.json",
    "bundle.sh",
    "mypy.ini",
    "requirements.txt",
    "README.md",
]
